In [1]:
from sklearn import tree, neighbors, svm, naive_bayes
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.cross_validation import cross_val_score

# Load pandas
import pandas as pd

# Load numpy
import numpy as np

path = r'C:\Users\FZ\Dropbox\FYP Master Degree\SRS\wordlist_140417.csv'
words = pd.read_csv(path)

words.head(5)

C:\WinPython64bit353\python-3.5.3.amd64\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


yang  sistem  akan  maklumat  papar  maklumbalas  dan  untuk  telah  mohon  \
0     0       0     0         0      0            2    0      1      0      0   
1     1       0     0         1      0            1    0      0      0      0   
2     2       1     0         0      0            1    0      1      0      0   
3     1       0     1         0      0            3    2      3      0      0   
4     2       0     1         0      0            1    1      0      0      0   

   ...    statistik  talian  tapak  tempatan  terdahulu  tinggi  transaksi  \
0  ...            0       0      0         0          0       0          0   
1  ...            0       0      0         0          0       0          0   
2  ...            0       0      0         0          0       0          0   
3  ...            0       0      0         0          0       0          0   
4  ...            0       0      0         0          0       0          0   

   video  www  CLASS  
0      0    0      N  
1      0    0      Y  
2      0    0      Y  
3      0    0      Y  
4      0    0      Y  

[5 rows x 406 columns]

In [2]:
# Create a dataframe with the four feature variables
df = pd.DataFrame(words, columns=words.columns)

words.head(5)

yang  sistem  akan  maklumat  papar  maklumbalas  dan  untuk  telah  mohon  \
0     0       0     0         0      0            2    0      1      0      0   
1     1       0     0         1      0            1    0      0      0      0   
2     2       1     0         0      0            1    0      1      0      0   
3     1       0     1         0      0            3    2      3      0      0   
4     2       0     1         0      0            1    1      0      0      0   

   ...    statistik  talian  tapak  tempatan  terdahulu  tinggi  transaksi  \
0  ...            0       0      0         0          0       0          0   
1  ...            0       0      0         0          0       0          0   
2  ...            0       0      0         0          0       0          0   
3  ...            0       0      0         0          0       0          0   
4  ...            0       0      0         0          0       0          0   

   video  www  CLASS  
0      0    0      N  
1      0    0      Y  
2      0    0      Y  
3      0    0      Y  
4      0    0      Y  

[5 rows x 406 columns]

In [3]:
#trained data sets : 75%
df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75

# View the top 20 rows
df.head(20)

yang  sistem  akan  maklumat  papar  maklumbalas  dan  untuk  telah  \
0      0       0     0         0      0            2    0      1      0   
1      1       0     0         1      0            1    0      0      0   
2      2       1     0         0      0            1    0      1      0   
3      1       0     1         0      0            3    2      3      0   
4      2       0     1         0      0            1    1      0      0   
5      1       0     0         1      0            1    1      0      0   
6      0       0     1         0      0            1    0      1      0   
7      4       0     1         0      0            4    0      1      0   
8      1       0     0         0      0            0    0      0      0   
9      0       0     0         0      0            0    1      1      2   
10     1       0     1         0      0            1    0      0      1   
11     1       0     0         0      0            1    0      0      0   
12     0       0     0         0      0            1    0      0      0   
13     0       1     1         0      0            0    0      0      1   
14     1       1     0         1      0            0    0      0      0   
15     0       0     0         0      0            0    0      0      0   
16     0       0     0         0      0            0    0      0      0   
17     1       1     5         3      0            0    2      0      1   
18     3       0     2         3      2            6    0      1      0   
19     2       3     3         3      0            0    1      0      1   

    mohon    ...     talian  tapak  tempatan  terdahulu  tinggi  transaksi  \
0       0    ...          0      0         0          0       0          0   
1       0    ...          0      0         0          0       0          0   
2       0    ...          0      0         0          0       0          0   
3       0    ...          0      0         0          0       0          0   
4       0    ...          0      0         0          0       0          0   
5       0    ...          0      0         0          0       0          0   
6       0    ...          0      0         0          0       0          0   
7       0    ...          0      0         0          0       0          0   
8       0    ...          0      0         0          0       0          0   
9       0    ...          0      0         0          0       0          0   
10      0    ...          0      0         0          0       0          0   
11      0    ...          0      0         0          0       0          0   
12      0    ...          0      0         0          1       0          0   
13      0    ...          0      0         0          0       0          0   
14      0    ...          0      0         0          0       0          0   
15      0    ...          0      0         0          0       0          0   
16      0    ...          0      0         0          0       0          0   
17      0    ...          0      0         0          0       0          0   
18      0    ...          0      0         0          0       0          0   
19      0    ...          0      0         0          0       0          0   

    video  www  CLASS  is_train  
0       0    0      N      True  
1       0    0      Y     False  
2       0    0      Y      True  
3       0    0      Y     False  
4       0    0      Y      True  
5       0    0      Y      True  
6       0    0      N      True  
7       0    0      Y      True  
8       0    0      N      True  
9       0    0      Y      True  
10      0    0      Y      True  
11      0    0      Y      True  
12      0    0      Y      True  
13      0    0      Y      True  
14      0    0      N      True  
15      0    0      N      True  
16      0    0      N      True  
17      0    0      Y      True  
18      0    0      Y     False  
19      0    0      Y      True  

[20 rows x 407 columns]

In [4]:
# Create two new dataframes, one with the training rows, one with the test rows
train, test = df[df['is_train']==True], df[df['is_train']==False]

# Show the number of observations for the test and training dataframes
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:', len(test))


Number of observations in the training data: 142
Number of observations in the test data: 38


In [5]:
# Create a list of the feature column's names
features = df.columns[:-2]

features

Index(['yang', 'sistem', 'akan', 'maklumat', 'papar', 'maklumbalas', 'dan',
       'untuk', 'telah', 'mohon',
       ...
       'sesesuatu', 'statistik', 'talian', 'tapak', 'tempatan', 'terdahulu',
       'tinggi', 'transaksi', 'video', 'www'],
      dtype='object', length=405)

In [6]:
# train['CLASS'] contains the string value. Before we can use it,
# we need to convert each string into a numeric value. So, in this case there
# are 2 values, which have been coded as 0 (Y) or 1 (N).
y = pd.factorize(train['CLASS'])[0]

y

array([0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0], dtype=int64)

In [7]:
test_y = pd.factorize(test['CLASS'])[0]

test_y

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [8]:
## CHALLENGE - create 5 classifiers
clf = tree.DecisionTreeClassifier()
clf1 = neighbors.KNeighborsClassifier()
clf2 = svm.SVC()
clf3 = naive_bayes.GaussianNB()
clf4 = RandomForestClassifier()

# Train the classifier to take the training features and learn how they relate
# to the training y (train['CLASS'])

#CHALLENGE - train them on our data
clf = clf.fit(train[features], y)
clf1 = clf1.fit(train[features], y)
clf2 = clf2.fit(train[features], y)
clf3 = clf3.fit(train[features], y)
clf4 = clf4.fit(train[features], y)

#CHALLENGE compare their results and print the best one!
prediction = clf.predict(test[features])
prediction1 = clf1.predict(test[features])
prediction2 = clf2.predict(test[features])
prediction3 = clf3.predict(test[features])
prediction4 = clf4.predict(test[features])

prediction

array([0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [9]:
prediction1

array([0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [10]:
prediction2

array([0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [11]:
prediction3

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [12]:
prediction4

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [13]:
# View the predicted probabilities of the first 5 observations
clf.predict_proba(test[features])[0:5]

array([[ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.]])

In [14]:
# View the predicted probabilities of the first 5 observations
clf1.predict_proba(test[features])[0:5]

array([[ 0.8,  0.2],
       [ 0.8,  0.2],
       [ 0.4,  0.6],
       [ 0.8,  0.2],
       [ 0.2,  0.8]])

In [15]:
# View the predicted probabilities of the first 5 observations
#clf2.predict_proba(test[features])[0:5]

In [16]:
# View the predicted probabilities of the first 5 observations
clf3.predict_proba(test[features])[0:5]

array([[ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.]])

In [17]:
# View the predicted probabilities of the first 5 observations
clf4.predict_proba(test[features])[0:5]

array([[ 0.37333333,  0.62666667],
       [ 0.15      ,  0.85      ],
       [ 0.3       ,  0.7       ],
       [ 0.15      ,  0.85      ],
       [ 0.2       ,  0.8       ]])

In [18]:
preds = words.CLASS[clf.predict(test[features])]

# View the PREDICTED CLASS for the first five observations
preds[0:5] #DecisionTreeClassifier

0    N
1    Y
0    N
1    Y
1    Y
Name: CLASS, dtype: object

In [19]:
preds1 = words.CLASS[clf1.predict(test[features])]

# View the PREDICTED CLASS for the first five observations
preds1[0:5] #KNeighborsClassifier

0    N
0    N
1    Y
0    N
1    Y
Name: CLASS, dtype: object

In [20]:
preds2 = words.CLASS[clf2.predict(test[features])]

# View the PREDICTED CLASS for the first five observations
preds2[0:5] #SVC

0    N
1    Y
1    Y
1    Y
1    Y
Name: CLASS, dtype: object

In [21]:
preds3 = words.CLASS[clf3.predict(test[features])]

# View the PREDICTED CLASS for the first five observations
preds3[0:5] #GaussianNB

1    Y
1    Y
1    Y
1    Y
1    Y
Name: CLASS, dtype: object

In [22]:
preds4 = words.CLASS[clf4.predict(test[features])]

# View the PREDICTED CLASS for the first five observations
preds4[0:5] #RandomForestClassifier

1    Y
1    Y
1    Y
1    Y
1    Y
Name: CLASS, dtype: object

In [23]:
# View the ACTUAL CLASS for the first 5 observations
test['CLASS'].head(5)

1     Y
3     Y
18    Y
28    Y
29    Y
Name: CLASS, dtype: object

In [24]:
# View a list of the features and their importance scores
list(zip(train[features], clf.feature_importances_)) #DecisionTreeClassifier

[('yang', 0.0),
 ('sistem', 0.45290447152590768),
 ('akan', 0.0),
 ('maklumat', 0.0),
 ('papar', 0.18763567720622948),
 ('maklumbalas', 0.0),
 ('dan', 0.05032174819924673),
 ('untuk', 0.0),
 ('telah', 0.0),
 ('mohon', 0.049953744278897635),
 ('guna', 0.0),
 ('boleh', 0.0),
 ('proses', 0.0),
 ('dalam', 0.0048398091342876613),
 ('perlu', 0.0),
 ('terima', 0.0),
 ('tugas', 0.0),
 ('kepada', 0.0),
 ('senarai', 0.0),
 ('pilih', 0.0),
 ('daftar', 0.0),
 ('tindakan', 0.0),
 ('tersebut', 0.0),
 ('semak', 0.0),
 ('hendaklah', 0.0),
 ('hantar', 0.0),
 ('oleh', 0.0),
 ('dari', 0.0),
 ('tidak', 0.015487389229720518),
 ('siasat', 0.0),
 ('simpan', 0.0),
 ('majikan', 0.0),
 ('ahli', 0.0),
 ('buat', 0.0),
 ('dengan', 0.062256998888702793),
 ('cetak', 0.0),
 ('pengadu', 0.0),
 ('emel', 0.0),
 ('ataupun', 0.0),
 ('sah', 0.0),
 ('status', 0.0),
 ('isi', 0.0),
 ('jika', 0.0),
 ('kemaskini', 0.0),
 ('lewat', 0.0),
 ('apabila', 0.0),
 ('adalah', 0.0230467101632746),
 ('dana', 0.0),
 ('bina', 0.0),
 ('mengi

In [31]:
# View a list of the features and their importance scores
list(zip(train[features], clf4.feature_importances_)) #RandomForestClassifier

[('yang', 0.0039221353289442297),
 ('sistem', 0.15183710679828732),
 ('akan', 0.033751578045322861),
 ('maklumat', 0.007963690496108752),
 ('papar', 0.097963820426977363),
 ('maklumbalas', 0.0097439548741119035),
 ('dan', 0.10842532023046365),
 ('untuk', 0.00059808439255079593),
 ('telah', 0.0049670663555737736),
 ('mohon', 0.018510354333088223),
 ('guna', 0.0026884615179557487),
 ('boleh', 0.0049395396419796298),
 ('proses', 0.021956752907324677),
 ('dalam', 0.0037060685719134713),
 ('perlu', 0.0010864460228794265),
 ('terima', 0.007866866477056993),
 ('tugas', 0.0023400486136859878),
 ('kepada', 0.014766211659253093),
 ('senarai', 0.0042547549811291279),
 ('pilih', 0.00047124408602373295),
 ('daftar', 0.0046305623554651178),
 ('tindakan', 0.00024476850415416977),
 ('tersebut', 0.020538876675196324),
 ('semak', 0.0),
 ('hendaklah', 0.018100852627671055),
 ('hantar', 0.0034404519892038245),
 ('oleh', 0.00060591761960703265),
 ('dari', 0.010257884092879806),
 ('tidak', 0.031476504239348

In [32]:
print ("Mean accuracy for DecisionTreeClassifier:")
print (clf.score(train[features], y)) 

Mean accuracy for DecisionTreeClassifier:
0.985915492958


In [33]:
print ("Mean accuracy for KNeighborsClassifier:")
print (clf1.score(train[features], y)) 

Mean accuracy for KNeighborsClassifier:
0.830985915493


In [34]:
print ("Mean accuracy for SVC:")
print (clf2.score(train[features], y)) 

Mean accuracy for SVC:
0.781690140845


In [35]:
print ("Mean accuracy for GaussianNB:")
print (clf3.score(train[features], y)) 

Mean accuracy for GaussianNB:
0.985915492958


In [36]:
print ("Mean accuracy for RandomForestClassifier:")
print (clf4.score(train[features], y)) 

Mean accuracy for RandomForestClassifier:
0.985915492958
