In [1]:
from sklearn import tree, neighbors, svm, naive_bayes
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.cross_validation import cross_val_score

# Load pandas
import pandas as pd

# Load numpy
import numpy as np

path = r'C:\Users\FZ\Dropbox\FYP Master Degree\SRS\wordlist_140417.csv'
words = pd.read_csv(path)

words.head(5)

C:\WinPython64bit353\python-3.5.3.amd64\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


yang  sistem  akan  maklumat  papar  maklumbalas  dan  untuk  telah  mohon  \
0     0       0     0         0      0            2    0      1      0      0   
1     1       0     0         1      0            1    0      0      0      0   
2     2       1     0         0      0            1    0      1      0      0   
3     1       0     1         0      0            3    2      3      0      0   
4     2       0     1         0      0            1    1      0      0      0   

   ...    statistik  talian  tapak  tempatan  terdahulu  tinggi  transaksi  \
0  ...            0       0      0         0          0       0          0   
1  ...            0       0      0         0          0       0          0   
2  ...            0       0      0         0          0       0          0   
3  ...            0       0      0         0          0       0          0   
4  ...            0       0      0         0          0       0          0   

   video  www  CLASS  
0      0    0      N  
1      0    0      Y  
2      0    0      Y  
3      0    0      Y  
4      0    0      Y  

[5 rows x 406 columns]

In [2]:
# Create a dataframe with the four feature variables
df = pd.DataFrame(words, columns=words.columns)

words.head(5)

yang  sistem  akan  maklumat  papar  maklumbalas  dan  untuk  telah  mohon  \
0     0       0     0         0      0            2    0      1      0      0   
1     1       0     0         1      0            1    0      0      0      0   
2     2       1     0         0      0            1    0      1      0      0   
3     1       0     1         0      0            3    2      3      0      0   
4     2       0     1         0      0            1    1      0      0      0   

   ...    statistik  talian  tapak  tempatan  terdahulu  tinggi  transaksi  \
0  ...            0       0      0         0          0       0          0   
1  ...            0       0      0         0          0       0          0   
2  ...            0       0      0         0          0       0          0   
3  ...            0       0      0         0          0       0          0   
4  ...            0       0      0         0          0       0          0   

   video  www  CLASS  
0      0    0      N  
1      0    0      Y  
2      0    0      Y  
3      0    0      Y  
4      0    0      Y  

[5 rows x 406 columns]

In [3]:
#trained data sets : 75%
df['is_train'] = np.random.uniform(0, 1, len(df)) <= .50

# View the top 20 rows
df.head(10)

yang  sistem  akan  maklumat  papar  maklumbalas  dan  untuk  telah  mohon  \
0     0       0     0         0      0            2    0      1      0      0   
1     1       0     0         1      0            1    0      0      0      0   
2     2       1     0         0      0            1    0      1      0      0   
3     1       0     1         0      0            3    2      3      0      0   
4     2       0     1         0      0            1    1      0      0      0   
5     1       0     0         1      0            1    1      0      0      0   
6     0       0     1         0      0            1    0      1      0      0   
7     4       0     1         0      0            4    0      1      0      0   
8     1       0     0         0      0            0    0      0      0      0   
9     0       0     0         0      0            0    1      1      2      0   

     ...     talian  tapak  tempatan  terdahulu  tinggi  transaksi  video  \
0    ...          0      0         0          0       0          0      0   
1    ...          0      0         0          0       0          0      0   
2    ...          0      0         0          0       0          0      0   
3    ...          0      0         0          0       0          0      0   
4    ...          0      0         0          0       0          0      0   
5    ...          0      0         0          0       0          0      0   
6    ...          0      0         0          0       0          0      0   
7    ...          0      0         0          0       0          0      0   
8    ...          0      0         0          0       0          0      0   
9    ...          0      0         0          0       0          0      0   

   www  CLASS  is_train  
0    0      N     False  
1    0      Y     False  
2    0      Y     False  
3    0      Y     False  
4    0      Y      True  
5    0      Y      True  
6    0      N      True  
7    0      Y      True  
8    0      N      True  
9    0      Y      True  

[10 rows x 407 columns]

In [4]:
# Create two new dataframes, one with the training rows, one with the test rows
train, test = df[df['is_train']==True], df[df['is_train']==False]

# Show the number of observations for the test and training dataframes
print('Number of observations in the training data:', len(train))
print('Number of observations in the test data:', len(test))

Number of observations in the training data: 93
Number of observations in the test data: 87


In [45]:
test_features = np.array([1,0,0,1,0,1,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
test_features = test_features.reshape(1,-1) 

test_class = np.array(['0']) # 0 (Y - non-ambiguity) or 1 (N - ambiguity)

test_features

array([[1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [46]:
test_class 

array(['0'], 
      dtype='<U1')

In [47]:
# Create a list of the feature column's names
features = df.columns[:-2]

features

Index(['yang', 'sistem', 'akan', 'maklumat', 'papar', 'maklumbalas', 'dan',
       'untuk', 'telah', 'mohon',
       ...
       'sesesuatu', 'statistik', 'talian', 'tapak', 'tempatan', 'terdahulu',
       'tinggi', 'transaksi', 'video', 'www'],
      dtype='object', length=405)

In [48]:
# train['CLASS'] contains the string value. Before we can use it,
# we need to convert each string into a numeric value. So, in this case there
# are 2 values, which have been coded as 0 (Y - non-ambiguity) or 1 (N - ambiguity).
y = pd.factorize(train['CLASS'])[0]

y

array([0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1], dtype=int64)

In [49]:
test_y = pd.factorize(test['CLASS'])[0]

test_y

array([0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [50]:
## CHALLENGE - create 5 classifiers
clf = tree.DecisionTreeClassifier()
clf1 = neighbors.KNeighborsClassifier()
clf2 = svm.SVC()
clf3 = naive_bayes.GaussianNB()
clf4 = RandomForestClassifier()

In [54]:
# Train the classifier to take the training features and learn how they relate
# to the training y (train['CLASS'])

#CHALLENGE - train them on our data
clf = clf.fit(train[features], y)
clf1 = clf1.fit(train[features], y)
clf2 = clf2.fit(train[features], y)
clf3 = clf3.fit(train[features], y)
clf4 = clf4.fit(train[features], y)

In [55]:
#CHALLENGE compare their results and print the best one!
prediction = clf.predict(test_features)
prediction1 = clf1.predict(test_features)
prediction2 = clf2.predict(test_features)
prediction3 = clf3.predict(test_features)
prediction4 = clf4.predict(test_features)

In [59]:
prediction

array([1], dtype=int64)

In [60]:
prediction1

array([1], dtype=int64)

In [61]:
prediction2

array([1], dtype=int64)

In [64]:
prediction3

array([0], dtype=int64)

In [65]:
prediction4

array([1], dtype=int64)